## Image generator

In [1]:
import sys
# sys.path.append('/home/jovyan/work')
sys.path.append('..')

import nima as nima

In [3]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from nima.model.data_generator import TrainDataGenerator, TestDataGenerator
from nima.utils.ava_dataset_utils import get_ava_csv_df, get_rating_columns

In [4]:
ava_csv_df = get_ava_csv_df()
ava_csv_df.head()

index  image_id  count_rating_1  count_rating_2  count_rating_3  \
0      1    953619               0               1               5   
1      2    953958              10               7              15   
2      3    954184               0               0               4   
3      4    954113               0               1               4   
4      5    953980               0               3               6   

   count_rating_4  count_rating_5  count_rating_6  count_rating_7  \
0              17              38              36              15   
1              26              26              21              10   
2               8              41              56              10   
3               6              48              37              23   
4              15              57              39               6   

   count_rating_8  count_rating_9  count_rating_10  tag_1  tag_2  challange_id  
0               6               5                1      1     22          1396  
1               8               1                2      1     21          1396  
2               3               4                0      0      0          1396  
3               5               2                2     15     21          1396  
4               1               1                1     22     38          1396

In [9]:
import nima.utils.ava_dataset_utils as ap

count_columns = get_rating_columns()
df_train, df_valid, df_test = ap.load_data('../data/AVA/', 1000)
print(f"{len(df_train)} - {len(df_test)} - {len(df_valid)} ")

	Number of samples picked 1000
760 - 50 - 190 


In [16]:
PROJECT_DIR = '../'
DATA_DIR = os.path.join(PROJECT_DIR, 'data/AVA/images')
image_files = os.listdir(DATA_DIR)

image_files[:5], count_columns

# df = ava_csv_df[['image_id']]
# df['ratings'] = ava_csv_df[count_columns].apply(lambda x : x.values.tolist(), axis=1)
# # count_columns
# df.head()

(['1000.jpg', '10000.jpg', '10002.jpg', '10003.jpg', '10005.jpg'],
 ['count_rating_1',
  'count_rating_2',
  'count_rating_3',
  'count_rating_4',
  'count_rating_5',
  'count_rating_6',
  'count_rating_7',
  'count_rating_8',
  'count_rating_9',
  'count_rating_10'])

#### Check the mechanism of TestDataGenerator

In [21]:
# from tensorflow.keras.applications.vgg19 import preprocess_input
# test_generator = TestDataGenerator(df_test, DATA_DIR, x_col='image_id', y_col=count_columns,
#                                    preprocess_input=preprocess_input, input_size=(224, 224, 3))

# we have 50 samples in the test df with batch size of 32 there will be 2 epochs
epochs, batch_size, indexes = 2, 32, np.arange(len(df_test))

for index in range(epochs):
    batch_indexes = indexes[index*batch_size: (index+1)*batch_size]
    batch_sample = df_test.iloc[batch_indexes]
    print(index, batch_indexes)


0 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
1 [32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
a = np.empty((2, 2,2))
b= np.random.random((2,2))
print(a)
a[0] = b
print(a)

[[[9.38867156e-001 3.69844453e-001]
  [8.20128947e-001 7.88819325e-001]]

 [[4.65108143e-310 4.94065646e-324]
  [4.65108143e-310 4.65108143e-310]]]
[[[4.83564096e-001 6.05833462e-001]
  [7.60223286e-001 2.30252526e-001]]

 [[4.65108143e-310 4.94065646e-324]
  [4.65108143e-310 4.65108143e-310]]]


In [22]:
batch_size = 32
index = 2
indexes = np.arange(len(df))
batch_indexes = indexes[index*batch_size: (index+1)*batch_size]
batch_sample = df.iloc[batch_indexes]
# batch_indexes
batch_sample[:5]

image_id                              ratings
64    954180   [0, 0, 3, 14, 35, 51, 10, 3, 1, 1]
65    954014    [0, 3, 7, 26, 57, 19, 2, 1, 1, 3]
66    954092   [0, 0, 3, 1, 26, 42, 30, 18, 6, 4]
67    954226  [9, 11, 24, 28, 28, 11, 5, 5, 0, 0]
68    953946    [0, 0, 4, 4, 34, 56, 14, 8, 5, 0]

In [23]:
npl = np.array(df.iloc[0,1])
npl/npl.sum()

array([0.        , 0.00806452, 0.04032258, 0.13709677, 0.30645161,
       0.29032258, 0.12096774, 0.0483871 , 0.04032258, 0.00806452])

In [5]:
from nima.model.data_generator import NimaDataGenerator
data_generator = NimaDataGenerator(pd.DataFrame(df), img_directory = DATA_DIR, x_col='image_id', y_col='ratings', preprocess_input=None, batch_size=32)

<class 'pandas.core.series.Series'>
Found 15084 valid image filenames belonging to 10 classes.


In [6]:
from sklearn.model_selection import train_test_split

df_train, df_valid = train_test_split(df, test_size=0.1)
df_train.head()

image_id                                ratings
9245     110995    [0, 1, 6, 31, 62, 74, 45, 17, 5, 4]
10418     12245     [1, 1, 1, 18, 36, 26, 15, 7, 1, 0]
8470     133904   [1, 7, 27, 78, 121, 74, 20, 3, 3, 1]
7878     118577  [20, 30, 61, 105, 73, 23, 9, 4, 1, 2]
1706     118049  [1, 3, 10, 34, 84, 77, 47, 24, 16, 9]

In [8]:
# Import the libraries 
from tensorflow.keras.layers import Dropout, Flatten, MaxPool2D, Conv2D, Dense
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from nima.model.loss import earth_movers_distance

model = Sequential()
model.add(Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(224, 224, 3)))
model.add(MaxPool2D(pool_size=2, strides=2))
model.add(Dropout(0.2))

model.add(Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(224, 224, 3)))
model.add(MaxPool2D(pool_size=2, strides=2))
model.add(Dropout(0.2))

model.add(Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(224, 224, 3)))
model.add(MaxPool2D(pool_size=2, strides=2))
model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(optimizer=Adam(), loss=earth_movers_distance)

ModuleNotFoundError: No module named 'src'

In [26]:
train_datagen = NimaDataGenerator(
    df_train,
    img_directory=DATA_DIR,
    x_col="image_id",
    y_col="ratings",
    preprocess_input=None,
    batch_size=32,
    input_size=(256, 256, 3),
    crop_size=(224, 224),
)

valid_datagen = NimaDataGenerator(
    df_valid,
    img_directory=DATA_DIR,
    x_col="image_id",
    y_col="ratings",
    preprocess_input=None,
    batch_size=32,
    input_size=(256, 256, 3),
    crop_size=(224, 224),
)

earlystopping = EarlyStopping(
    min_delta=0.001, monitor="val_loss", patience=4, restore_best_weights=True
)

CKPT_DIR = "src/weights"
checkpoint = ModelCheckpoint(
    filepath=CKPT_DIR,
    save_weights_only=True,
    monitor="val_loss",
    mode="max",
    save_best_only=True,
)

ModuleNotFoundError: No module named 'nima'

In [118]:
# Train and fit model
history = model.fit(
    train_datagen,
    validation_data=valid_datagen,
    callbacks=[earlystopping, checkpoint],
#     use_multiprocessing=True,
    epochs=50,
    verbose=1,
)


TypeError: 'numpy.float64' object cannot be interpreted as an integer